In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
# creating tensors with tf.conatant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor. (ndim)
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# creating a matrics 
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrax = tf.constant([[10. ,7.],
                              [10., 7.],
                              [10., 7.], dtype=tf.float16)

SyntaxError: ignored

In [ ]:
tensor = tf.constant([[[1, 2 ,3],
            [4, 5, 6]],
           [[7, 8 ,9],
            [10, 11, 12]],
          [[13, 14, 15],
           [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Creating tensor with tf.Variable


In [ ]:
# creating the same tensor
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
# unchangeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Here the unchangeable tensor cannot be changed as it is a constant 

### Creating randon tensors

Tensor of arbitary size that contains random size and random number


In [ ]:
#Create 2 random tensors 

random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape = (3, 2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3, 2))
random1, random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

### Shufflle the order of the tensor

In [ ]:
# shuffle the tensor(Useful when we want to shuffle the order of data)
not_shuffled = tf.constant([[10, 7],
                            [1, 7],
                            [10, 17]])

not_shuffled.ndim

2

Randomly shuffles a tensor along its first dimension.

In [ ]:
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  7],
       [10, 17]], dtype=int32)>

If we want shuffle ours tensors in the same order than we have to set glodal level seed and operational level seed 

> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."


### Other ways to make tensor 

In [ ]:
#Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#creating tensor of all zeros
tf.zeros(shape=(3,4))
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Main difference betweeen NumPy arrays and TensorFlow tensor is tensor can be run faster on GPU

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A
# X = tf.constant(some_matrix) Capital for matrix or tensor
# y = tf.constant(vector) Small for vector 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
test = tf.random.shuffle(A)
test

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]], dtype=int32)>

### Having More Information from Tensor

* Shape
* Size
* Axis or Dimension
* Size

In [ ]:
# Create a rank 4 tensor

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor).numpy()

(TensorShape([2, 3, 4, 5]), 4, 120)

In [ ]:
rank_4_tensor.shape[0]
rank_4_tensor.shape[-1]


5

### Indexing tensors is just like Python list

In [ ]:
# get the first 2 elements of each dimension
rank_4_tensor[:2, :3, :2, :2]

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Getting the 1st elements from each dimension except the second last one
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating Tensors (Tensor Operations)




** Basic Operation **
`+`,``-``,``*``,``/`


In [ ]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor = tensor + 10
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [ ]:
tensor / 2 

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10. ,  8.5],
       [ 6.5,  7. ]])>

In [ ]:
# We can also use the built-in function
tf.math.multiply(tensor, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

**Matrix Multiplication**

In machine learning this is  the most common operation 

There are 2 rule in this 

1. The inner dimension must match 
2. The resulting matrix has the shape of the outer dimension 

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
print(tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


In [ ]:
# Mstrix multiplication can also be done by @ 
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
X = tf.constant([[10, 7],
                      [3, 4],
                 [2, 3]])
Y = tf.constant([[10, 3],
                      [5, 4],
                 [8, 9]])
X.shape
Y.shape

TensorShape([3, 2])

**The Dot Product**

Matrix Multiplication is also reffered to as dot product.

This can be done as follows:

* `tf.matmul()`
* `tf.tensordot()`


In [ ]:
# Perfom the dot product on X and Y 

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[131,  60],
       [114,  64]], dtype=int32)>

In [ ]:
# Y (transposed)
tf.matmul(X, tf.transpose(Y)), tf.matmul(X, tf.reshape(Y, shape=(2,3)))

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[121,  78, 143],
        [ 42,  31,  60],
        [ 29,  22,  43]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[128,  86, 113],
        [ 46,  41,  51],
        [ 32,  30,  37]], dtype=int32)>)

Here the reshape gets tensor to the shape by splitting the data randomly and the transpose does by getting the transpose


In [ ]:
Y, tf.transpose(Y), tf.reshape(Y, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  3],
        [ 5,  4],
        [ 8,  9]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  5,  8],
        [ 3,  4,  9]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  3,  5],
        [ 4,  8,  9]], dtype=int32)>)

Genrally when performing the multiplication do transpose 

**Changing The Datatype of tensor**

In [ ]:
#Create a new tensor with default datatype (float32)

B = tf.constant([1, 7])
B.dtype

tf.int32

In [ ]:
B = tf.cast(B, dtype=tf.int16)
B

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 7], dtype=int16)>

### Aggregating Tensor

Aggregating tensor = condensing from multiple values to a smaller amount of values


In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Forms of Aggregation

* Get the minimun
* Get the Maximum
* Get the mean of tensor
* Get the sum of tensor 


In [ ]:
#Create a random tensor

E= tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([72,  9, 93, 73, 53, 54, 94, 83, 84, 69, 95, 71, 37, 91, 31, 59, 32,
       38, 11, 13, 47, 99,  5, 45, 11, 30, 21,  1, 97, 70, 65, 17, 19, 33,
       49, 59, 87, 46, 85, 76, 93,  8, 66, 38, 99, 88, 32, 84, 78, 60])>

In [ ]:
#Find min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# find max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#Mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2770>

In [ ]:
# Variance 
import tensorflow_probability as tfp
tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=int64, numpy=883>

### For finding the standard deviation the input must be in float32

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.716661>

In [ ]:
# Find the variance 
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=883.08>

### Findind Positional min

In [ ]:
#Create a random tensor 
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the positional minimun 

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

### Squeezing the tensor (Removing all the single dimension)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.ndim, G.shape

(5, TensorShape([1, 1, 1, 1, 50]))

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

In [ ]:
# Create a list of indices 

some_list = [0, 1, 2, 3]

#One hot encode

tf.one_hot(some_list,depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify on val and off val

tf.one_hot(some_list, depth=4, on_value="I love Deep learing", off_value="Hi")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love Deep learing', b'Hi', b'Hi', b'Hi'],
       [b'Hi', b'I love Deep learing', b'Hi', b'Hi'],
       [b'Hi', b'Hi', b'I love Deep learing', b'Hi'],
       [b'Hi', b'Hi', b'Hi', b'I love Deep learing']], dtype=object)>

### Tensor and Numpy

In [ ]:
# Create a tensor directly from numpy array

J = tf.constant(np.array([3., 7., 10.,]))
J


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert back to numpy 
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy()

array([ 3.,  7., 10.])

In [ ]:
# The default type of each are slightly different 
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.,])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)